/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProjectPackage;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.text.*;
import java.awt.print.*;

/**
 *
 * @author DELL
 */
public class BookingReceipt extends javax.swing.JFrame {

    /**
     * Creates new form Receipt
     */
    private int source;
    private String booking_id;
    private String pbooking_id;
    public BookingReceipt() {
        initComponents();
        display();
    }
    
    public BookingReceipt(String booking_id, int source) {
        initComponents();
        this.booking_id = booking_id;
        this.pbooking_id = booking_id;
        this.source = source;
        display();
    }
    
    public Connection connect()
    {
        Connection con = null;
        String driver = "com.mysql.cj.jdbc.Driver";
        try
        {           
            con = DriverManager.getConnection("jdbc:mysql://localhost:3308/fp_hotel_management_system", "root", "root123");
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        return con;
    }
    
    public void display(){
        Connection con = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        try{
            con = connect();
            if(source == 1){
                String sql = "SELECT booking_id, GROUP_CONCAT(room_id) AS room_ids, cus_id, booking_date, stay_period FROM room_bookings WHERE booking_id = ? GROUP BY booking_id, cus_id, booking_date, stay_period";
                ps = con.prepareStatement(sql);
                ps.setString(1, booking_id);
                rs = ps.executeQuery();
                while(rs.next()){
                    lbl_bookingId.setText("Booking ID: " + rs.getString("booking_id"));
                    lbl_cusId.setText("Customer ID: " +rs.getString("cus_id"));
                    lbl_roomId.setText("Room IDs: " +rs.getString("room_ids"));
                    lbl_bookingDate.setText("Booking Date: " +rs.getString("booking_date"));
                }
            }
            else if(source == 2){
                String sql = "select pbooking_id, GROUP_CONCAT(package_id) as package_ids, cus_id, booking_date, people_count from package_bookings where pbooking_id = ? GROUP BY pbooking_id, cus_id, booking_date, people_count";
                ps = con.prepareStatement(sql);
                ps.setString(1, pbooking_id);
                rs = ps.executeQuery();
                while(rs.next()){
                    lbl_bookingId.setText("Booking ID: " + rs.getString("pbooking_id"));
                    lbl_cusId.setText("Customer ID: " + rs.getString("cus_id"));
                    lbl_roomId.setText("Package IDs: " + rs.getString("package_ids"));
                    lbl_bookingDate.setText("Booking Date: " + rs.getString("booking_date") + "\t\tPeople Count: " + rs.getString("people_count"));
                }
            }
        }
        catch(SQLException e){
            e.printStackTrace();
        }
        finally{
            try{
                con.close();
                ps.close();
                rs.close();
            }
            catch(SQLException e){
                e.printStackTrace();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_printReceipt = new javax.swing.JButton();
        btn_goHome = new javax.swing.JButton();
        bookingreceipt_panel = new javax.swing.JPanel();
        lbl_bookingId = new javax.swing.JLabel();
        lbl_cusId = new javax.swing.JLabel();
        lbl_roomId = new javax.swing.JLabel();
        lbl_bookingDate = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setFocusable(false);

        jPanel2.setBackground(new java.awt.Color(255, 204, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesandIcons/receipt_9413543.png"))); // NOI18N
        jLabel1.setText("Your Booking Receipt");
        jLabel1.setIconTextGap(20);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        btn_printReceipt.setBackground(new java.awt.Color(255, 204, 0));
        btn_printReceipt.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btn_printReceipt.setForeground(new java.awt.Color(255, 255, 255));
        btn_printReceipt.setText("Print the Receipt");
        btn_printReceipt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_printReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printReceiptActionPerformed(evt);
            }
        });

        btn_goHome.setBackground(new java.awt.Color(0, 0, 0));
        btn_goHome.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btn_goHome.setForeground(new java.awt.Color(255, 255, 255));
        btn_goHome.setText("Go back to Home Page");
        btn_goHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_goHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_goHomeActionPerformed(evt);
            }
        });

        bookingreceipt_panel.setBackground(new java.awt.Color(255, 255, 255));
        bookingreceipt_panel.setForeground(new java.awt.Color(0, 0, 0));

        lbl_bookingId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_bookingId.setForeground(new java.awt.Color(0, 0, 0));
        lbl_bookingId.setText("Booking ID:");
        lbl_bookingId.setFocusable(false);

        lbl_cusId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_cusId.setForeground(new java.awt.Color(0, 0, 0));
        lbl_cusId.setText("Customer ID:");
        lbl_cusId.setFocusable(false);

        lbl_roomId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_roomId.setForeground(new java.awt.Color(0, 0, 0));
        lbl_roomId.setText("Room Id:");
        lbl_roomId.setFocusable(false);

        lbl_bookingDate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_bookingDate.setForeground(new java.awt.Color(0, 0, 0));
        lbl_bookingDate.setText("Booking Date:");
        lbl_bookingDate.setFocusable(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Booking Receipt");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("**********************************************************************************");

        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea1.setRows(5);
        jTextArea1.setText("Thank you for booking at our hotel.You can cancel the booking till 2 days before your\nbooking date.\nIf you want to do so, please contact our reception\n09-258494078, 09797191253\nPlease note that you need this receipt when checking in. Therefore please take a \nscreenshot or print this receipt. Thanks for your cooperation.");
        jTextArea1.setFocusable(false);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout bookingreceipt_panelLayout = new javax.swing.GroupLayout(bookingreceipt_panel);
        bookingreceipt_panel.setLayout(bookingreceipt_panelLayout);
        bookingreceipt_panelLayout.setHorizontalGroup(
            bookingreceipt_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingreceipt_panelLayout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookingreceipt_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bookingreceipt_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookingreceipt_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(bookingreceipt_panelLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(bookingreceipt_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbl_cusId, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_bookingId, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_roomId, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_bookingDate, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        bookingreceipt_panelLayout.setVerticalGroup(
            bookingreceipt_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookingreceipt_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_bookingId, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_cusId, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_roomId, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_bookingDate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bookingreceipt_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(btn_printReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113)
                        .addComponent(btn_goHome, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bookingreceipt_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_printReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_goHome, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_goHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_goHomeActionPerformed
        // TODO add your handling code here:
        WelcomeForm wf = new WelcomeForm();
        CustomerInfo ci = new CustomerInfo();       
        ci.hide();
        this.hide();
        wf.setVisible(true);
    }//GEN-LAST:event_btn_goHomeActionPerformed

    private void btn_printReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printReceiptActionPerformed
        // TODO add your handling code here:
        try{
            PrinterJob printerJob = PrinterJob.getPrinterJob();
            printerJob.setJobName("Print Booking Receipt");
            printerJob.setPrintable(new Printable(){
                @Override
                public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
                    if(pageIndex > 0){
                        return Printable.NO_SUCH_PAGE;
                    }
                    
                    Graphics2D g2D = (Graphics2D) graphics;
                    // Calculate the scaling factor to fit the panel into the printable area
                    double scaleFactor = Math.min(
                            pageFormat.getImageableWidth() / bookingreceipt_panel.getWidth(),
                            pageFormat.getImageableHeight() / bookingreceipt_panel.getHeight()
                    );

                    // Calculate the x and y offsets to center the panel on the page
                    double xOffset = (pageFormat.getImageableWidth() - bookingreceipt_panel.getWidth() * scaleFactor) / 2;
                    double yOffset = (pageFormat.getImageableHeight() - bookingreceipt_panel.getHeight() * scaleFactor) / 2;

                    // Translate and scale the graphics context
                    g2D.translate(pageFormat.getImageableX() + xOffset, pageFormat.getImageableY() + yOffset);
                    g2D.scale(scaleFactor, scaleFactor);
                    
                    bookingreceipt_panel.print(g2D);
                    
                    return Printable.PAGE_EXISTS;
                }            
            });
            
            boolean confirm = printerJob.printDialog();
            if(confirm){
                printerJob.print();
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_printReceiptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookingReceipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bookingreceipt_panel;
    private javax.swing.JButton btn_goHome;
    private javax.swing.JButton btn_printReceipt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbl_bookingDate;
    private javax.swing.JLabel lbl_bookingId;
    private javax.swing.JLabel lbl_cusId;
    private javax.swing.JLabel lbl_roomId;
    // End of variables declaration//GEN-END:variables
}
