/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProjectPackage;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author DELL
 */
public class ListedPackageInfo extends javax.swing.JFrame {

    /**
     * Creates new form ListedPackageInfo
     */
    public ListedPackageInfo() {
        initComponents();
        display();
    }
    
    public Connection connect()
    {
        Connection con = null;
        String driver = "com.mysql.cj.jdbc.Driver";
        try
        {           
            con = DriverManager.getConnection("jdbc:mysql://localhost:3308/fp_hotel_management_system", "root", "root123");
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        return con;
    }
    
    public String[] getID(){
        try{
            Connection con = connect();
            String sql = "Select package_id from reserved_temp";
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            
            // Create a list to store room IDs dynamically
            List<String> idList = new ArrayList<>();

            // Iterate through the result set to retrieve room IDs
            while (rs.next()) {
                String roomid = rs.getString("package_id");
                idList.add(roomid);
            }

            // Convert the list to an array
            String[] ids = idList.toArray(new String[0]);
            return ids;
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            return null;
        }     
    }
    
    public void display(){
        String[] packageids = getID();
        DefaultTableModel model = (DefaultTableModel) table_listedPackages.getModel();
        try{
            Connection con = connect();
            model.setRowCount(0);
            String sql = "select package_id, package_name, package_type, package_price, services from packages where package_id = ?";
            for(String id : packageids){
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setString(1, id);
                ResultSet rs = ps.executeQuery();
                while(rs.next()){
                    Object[] dataRow = {
                        rs.getString("package_id"),
                        rs.getString("package_name"),
                        rs.getString("package_type"),
                        rs.getString("package_price"),
                        rs.getString("services")
                    };
                    model.addRow(dataRow);
                }
                table_listedPackages.setModel(model);
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_listedPackages = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        lbl_packageName = new javax.swing.JLabel();
        lbl_packageType = new javax.swing.JLabel();
        lbl_packagePrice = new javax.swing.JLabel();
        lbl_service = new javax.swing.JLabel();
        btn_bookMoreP = new javax.swing.JButton();
        btn_removeP = new javax.swing.JButton();
        btn_fillCusInfo = new javax.swing.JButton();

        jButton3.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(255, 204, 0));
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Your Listed Packages");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        table_listedPackages.setBackground(new java.awt.Color(255, 255, 255));
        table_listedPackages.setForeground(new java.awt.Color(0, 0, 0));
        table_listedPackages.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Package ID", "Package Name", "Package Type", "Package Price", "Services"
            }
        ));
        table_listedPackages.setSelectionBackground(new java.awt.Color(5, 124, 124));
        table_listedPackages.setSelectionForeground(new java.awt.Color(255, 255, 255));
        table_listedPackages.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_listedPackagesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_listedPackages);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("You Can Modify Your List");

        lbl_packageName.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        lbl_packageName.setForeground(new java.awt.Color(0, 0, 0));
        lbl_packageName.setText("Package Name:");

        lbl_packageType.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        lbl_packageType.setForeground(new java.awt.Color(0, 0, 0));
        lbl_packageType.setText("Package Type:");

        lbl_packagePrice.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        lbl_packagePrice.setForeground(new java.awt.Color(0, 0, 0));
        lbl_packagePrice.setText("Package Price:");

        lbl_service.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        lbl_service.setForeground(new java.awt.Color(0, 0, 0));
        lbl_service.setText("Service:");

        btn_bookMoreP.setBackground(new java.awt.Color(255, 204, 0));
        btn_bookMoreP.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btn_bookMoreP.setForeground(new java.awt.Color(255, 255, 255));
        btn_bookMoreP.setText("Book More Packages");
        btn_bookMoreP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bookMorePActionPerformed(evt);
            }
        });

        btn_removeP.setBackground(new java.awt.Color(0, 0, 0));
        btn_removeP.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btn_removeP.setForeground(new java.awt.Color(255, 255, 255));
        btn_removeP.setText("Remove Package From List");
        btn_removeP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removePActionPerformed(evt);
            }
        });

        btn_fillCusInfo.setBackground(new java.awt.Color(255, 204, 0));
        btn_fillCusInfo.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btn_fillCusInfo.setForeground(new java.awt.Color(255, 255, 255));
        btn_fillCusInfo.setText("Fill Customer Information to Confirm Booking");
        btn_fillCusInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fillCusInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_packageName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_packageType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_packagePrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_service, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_fillCusInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_removeP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_bookMoreP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 17, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_packageName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_packageType, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_packagePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_service, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_bookMoreP, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_removeP, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(btn_fillCusInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void table_listedPackagesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_listedPackagesMouseClicked
        // TODO add your handling code here:
        TableModel model = table_listedPackages.getModel();
        int index = table_listedPackages.getSelectedRow();
        lbl_packageName.setText("Package Name: " + model.getValueAt(index, 1).toString());
        lbl_packageType.setText("Package Type: " + model.getValueAt(index, 2).toString());
        lbl_packagePrice.setText("Package Price: " + model.getValueAt(index, 3).toString() + " per day");
        lbl_service.setText("Service: " + model.getValueAt(index, 4).toString());
    }//GEN-LAST:event_table_listedPackagesMouseClicked

    private void btn_bookMorePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bookMorePActionPerformed
        // TODO add your handling code here:
        ViewPackages VP = new ViewPackages();
        VP.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btn_bookMorePActionPerformed

    private void btn_removePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removePActionPerformed
        // TODO add your handling code here:
        TableModel model = table_listedPackages.getModel();
        int index = table_listedPackages.getSelectedRow();
        String packageid = model.getValueAt(index, 0).toString();
        int result = JOptionPane.showConfirmDialog(null, "Do you really want to remove this package from the booking list?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if(result == JOptionPane.YES_OPTION){
            try{
                Connection con = connect();
                String sql = "delete from reserved_temp where package_id = ?";
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setString(1, packageid);
                ps.execute();
                JOptionPane.showMessageDialog(null, "The package has been removed from the booking list", "Removed From List", JOptionPane.INFORMATION_MESSAGE);
                display();
                lbl_packageName.setText("Package Name: ");
                lbl_packageType.setText("Package Type: ");
                lbl_packagePrice.setText("Package Price: ");
                lbl_service.setText("Service: ");
            }
            catch(Exception e){
                e.printStackTrace();
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Thank you for choosing our hotel!\nWe appreciate your decision not to cancel your room booking.\nWe look forward to ensuring a delightful stay for you.",
            "Thank You", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_removePActionPerformed

    private void btn_fillCusInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fillCusInfoActionPerformed
        // TODO add your handling code here:
        if(table_listedPackages.getRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Please choose some packages to book first.", "Warning", JOptionPane.WARNING_MESSAGE);
            ViewPackages VP = new ViewPackages();
            VP.setVisible(true);
            this.hide();
        }
        else{
            int FROM_PACKAGE = 2;
            CustomerInfo CI = new CustomerInfo(FROM_PACKAGE);
            CI.setVisible(true);
            this.hide();
        }
    }//GEN-LAST:event_btn_fillCusInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListedPackageInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListedPackageInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListedPackageInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListedPackageInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListedPackageInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bookMoreP;
    private javax.swing.JButton btn_fillCusInfo;
    private javax.swing.JButton btn_removeP;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_packageName;
    private javax.swing.JLabel lbl_packagePrice;
    private javax.swing.JLabel lbl_packageType;
    private javax.swing.JLabel lbl_service;
    private javax.swing.JTable table_listedPackages;
    // End of variables declaration//GEN-END:variables
}
