/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProjectPackage;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author DELL
 */
public class ReservedRoomInfo extends javax.swing.JFrame {

    /**
     * Creates new form ReservedRoomInfo
     */
    public ReservedRoomInfo() {
        initComponents();
        display();
    }
    
    public Connection connect()
    {
        Connection con = null;
        String driver = "com.mysql.cj.jdbc.Driver";
        try
        {           
            con = DriverManager.getConnection("jdbc:mysql://localhost:3308/fp_hotel_management_system", "root", "root123");
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        return con;
    }
    
    public void display()
    {
        String[] ids = getID();
        DefaultTableModel model = (DefaultTableModel)table_reservedDataTemp.getModel();
        try
        {
            model.setRowCount(0);
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = connect();
            String sql = "Select room_id, room_no, room_type, room_price, description, bed from room where room_id = ?";
            for (String id : ids) {
                PreparedStatement pstmt = con.prepareStatement(sql);
                pstmt.setString(1, id);
                ResultSet rs = pstmt.executeQuery();
                while (rs.next()) {
                Object[] rowData = {
                    rs.getString("room_id"),
                    rs.getString("room_no"),
                    rs.getString("room_type"),
                    rs.getString("room_price"),
                    rs.getString("description"),
                    rs.getString("bed")
                };
                model.addRow(rowData);
            }
                table_reservedDataTemp.setModel(model);
           }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
     //to get the id of reserved_room from the reserved_temp table
    public String[] getID(){
        try{
            Connection con = connect();
            String sql = "Select room_id from reserved_temp";
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            
            // Create a list to store room IDs dynamically
            List<String> idList = new ArrayList<>();

            // Iterate through the result set to retrieve room IDs
            while (rs.next()) {
                String roomid = rs.getString("room_id");
                idList.add(roomid);
            }

            // Convert the list to an array
            String[] ids = idList.toArray(new String[0]);
            return ids;
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            return null;
        }     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_reservedDataTemp = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btn_bookMore = new javax.swing.JButton();
        btn_remove = new javax.swing.JButton();
        lbl_roomNo = new javax.swing.JLabel();
        lbl_roomType = new javax.swing.JLabel();
        btn_fillInfo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(255, 204, 0));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Trajan Pro", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Your Listed Rooms...");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        table_reservedDataTemp.setBackground(new java.awt.Color(255, 255, 255));
        table_reservedDataTemp.setForeground(new java.awt.Color(0, 0, 0));
        table_reservedDataTemp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "room_id", "room_no", "room_type", "room_price", "description", "bed"
            }
        ));
        table_reservedDataTemp.setSelectionBackground(new java.awt.Color(5, 124, 124));
        table_reservedDataTemp.setSelectionForeground(new java.awt.Color(255, 255, 255));
        table_reservedDataTemp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_reservedDataTempMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_reservedDataTemp);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("You can modify your  reservation");

        btn_bookMore.setBackground(new java.awt.Color(255, 204, 0));
        btn_bookMore.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        btn_bookMore.setForeground(new java.awt.Color(255, 255, 255));
        btn_bookMore.setText("Book More Rooms");
        btn_bookMore.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_bookMore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bookMoreActionPerformed(evt);
            }
        });

        btn_remove.setBackground(new java.awt.Color(0, 0, 0));
        btn_remove.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        btn_remove.setForeground(new java.awt.Color(255, 255, 255));
        btn_remove.setText("Remove From Booking List");
        btn_remove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeActionPerformed(evt);
            }
        });

        lbl_roomNo.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lbl_roomNo.setForeground(new java.awt.Color(0, 0, 0));
        lbl_roomNo.setText("Room Number");

        lbl_roomType.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lbl_roomType.setForeground(new java.awt.Color(0, 0, 0));
        lbl_roomType.setText("Room Type");

        btn_fillInfo.setBackground(new java.awt.Color(255, 204, 0));
        btn_fillInfo.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        btn_fillInfo.setForeground(new java.awt.Color(255, 255, 255));
        btn_fillInfo.setText("Fill Required Information to Confirm Reservation");
        btn_fillInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_fillInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fillInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 665, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_bookMore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_roomNo)
                    .addComponent(lbl_roomType)
                    .addComponent(btn_fillInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_roomNo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(lbl_roomType, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_bookMore, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(btn_fillInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_fillInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fillInfoActionPerformed
        // TODO add your handling code here:
        if(table_reservedDataTemp.getRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Please Select rooms to book first.", "Warning", JOptionPane.WARNING_MESSAGE);
            ViewRooms vr = new ViewRooms();
            vr.setVisible(true);
            this.hide();
        }
        else{
            CustomerInfo Cusinfo = new CustomerInfo();
            Cusinfo.setVisible(true);
            this.hide();
        }       
    }//GEN-LAST:event_btn_fillInfoActionPerformed

    private void btn_bookMoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bookMoreActionPerformed
        // TODO add your handling code here:
        ViewRooms VR = new ViewRooms();
        VR.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btn_bookMoreActionPerformed

    private void table_reservedDataTempMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_reservedDataTempMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)table_reservedDataTemp.getModel();
        int index = table_reservedDataTemp.getSelectedRow();
        String id = model.getValueAt(index, 0).toString();
        lbl_roomNo.setText("Room Number: " + model.getValueAt(index, 1).toString());
        lbl_roomType.setText("Room Type: " + model.getValueAt(index, 2).toString());
    }//GEN-LAST:event_table_reservedDataTempMouseClicked

    private void btn_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)table_reservedDataTemp.getModel();
        int index = table_reservedDataTemp.getSelectedRow();
        String id = model.getValueAt(index, 0).toString();
        try{
            //first confirm the remove
            int result = JOptionPane.showConfirmDialog(null, "Do you really want to remove this room from the booking list?", "Confrim Message", JOptionPane.YES_NO_OPTION);
            //if customer chose yes, remove from the table
            if(result == JOptionPane.YES_OPTION){
                Connection con = connect();
                //first remove the room from the booking list
                String sql = "delete from reserved_temp where room_id = ?";
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setString(1, id);
                ps.execute();
                
                
                //update the status of the room
                String updateStatus = "update room set status = 'Available' where room_id = ?";
                PreparedStatement updatePs = con.prepareStatement(updateStatus);
                updatePs.setString(1, id);
                updatePs.executeUpdate();
                display();
                lbl_roomNo.setText("");
                lbl_roomType.setText("");
                
                //show a message to the customer
                JOptionPane.showMessageDialog(null, "The room has been removed from the booking list!");                
            }
            else{
                JOptionPane.showMessageDialog(null, "Thank you for choosing our hotel!\nWe appreciate your decision not to cancel your room booking.\nWe look forward to ensuring a delightful stay for you.",
                "Thank You", JOptionPane.INFORMATION_MESSAGE);
            }
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_removeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservedRoomInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservedRoomInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservedRoomInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservedRoomInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservedRoomInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bookMore;
    private javax.swing.JButton btn_fillInfo;
    private javax.swing.JButton btn_remove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_roomNo;
    private javax.swing.JLabel lbl_roomType;
    private javax.swing.JTable table_reservedDataTemp;
    // End of variables declaration//GEN-END:variables
}
